### ISSUE TITLE
main versus mainly

### ISSUE THREAD

**Issue by azharshahstl** [learn-co-curriculum/regex-match-scan-grep-methods-readme#8]
SCAN
The scan method returns an array of all items in your string that match a given Regular Expression. For example:

"The rain in Spain lies mainly in the plain".scan(/\w+ain/)
=> ["rain", "Spain", "main", "plain"]

Shouldn't the array include "mainly", not "main"?

**Comment by morgvanny** [comment]
scan doesn't really differentiate between words unless you specify in your regex, so it's just going to pull out the 'ain' and the letter preceding it, and put that letter first. Hence, 'main' instead of grabbing any characters after what it's looking for. To get 'mainly' you'd want to specify that you want to grab whatever comes after 'ain' until it encounters a space. So you'd want the regex to look something like this if you wanted to pull out 'mainly': /\w+ain\w*/
